export const FETCH_VENDOR_BY_ID = 'FETCH_VENDOR_BY_ID';
export const CHANGE_VENDOR_BY_ID ='CHANGE_VENDOR_BY_ID'
export const ADD_PRODUCT_TO_CARD ='ADD_PRODUCT_TO_CARD'
export const REMOVE_PRODUCT_TO_CARD = 'REMOVE_PRODUCT_TO_CARD'
export  const LOAD_DATA_FROM_LOCAL_STORAGE='LOAD_DATA_FROM_LOCAL_STORAGE'
export const CLEAR_CART_DATA ='CLEAR_CART_DATA'